name: xcode_parser
description: Reading and analyzing the contents of .pbxproj files. Modifying project settings and configurations. Saving changes to .pbxproj files.
version: 1.3.1
repository: https://github.com/EclipseAndrey/xcode_parser
homepage: https://github.com/EclipseAndrey/xcode_parser

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
